/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(time_sink_c_proc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3ee60702342a877a505b24ea096beb3b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <bokehgui/time_sink_c_proc.h>
// pydoc.h is automatically generated in the build directory
#include <time_sink_c_proc_pydoc.h>

void bind_time_sink_c_proc(py::module& m)
{

    using time_sink_c_proc    = ::gr::bokehgui::time_sink_c_proc;


    py::class_<time_sink_c_proc, gr::bokehgui::base_sink<std::complex<float> >,
        std::shared_ptr<time_sink_c_proc>>(m, "time_sink_c_proc", D(time_sink_c_proc))

        .def(py::init(&time_sink_c_proc::make),
           py::arg("size"),
           py::arg("samp_rate"),
           py::arg("name"),
           py::arg("nconnections"),
           D(time_sink_c_proc,make)
        )
        




        
        .def("get_tags",&time_sink_c_proc::get_tags,       
            D(time_sink_c_proc,get_tags)
        )


        
        .def("set_size",&time_sink_c_proc::set_size,       
            py::arg("newsize"),
            D(time_sink_c_proc,set_size)
        )


        
        .def("set_samp_rate",&time_sink_c_proc::set_samp_rate,       
            py::arg("samp_rate"),
            D(time_sink_c_proc,set_samp_rate)
        )


        
        .def("get_samp_rate",&time_sink_c_proc::get_samp_rate,       
            D(time_sink_c_proc,get_samp_rate)
        )


        
        .def("reset",&time_sink_c_proc::reset,       
            D(time_sink_c_proc,reset)
        )


        
        .def("set_trigger_mode",&time_sink_c_proc::set_trigger_mode,       
            py::arg("mode"),
            py::arg("slope"),
            py::arg("level"),
            py::arg("delay"),
            py::arg("channel"),
            py::arg("tag_key"),
            D(time_sink_c_proc,set_trigger_mode)
        )

        ;




}








