/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(vec_sink_c_proc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0230b3ea4add6cbc7923120461cd0ef8)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <bokehgui/vec_sink_c_proc.h>
// pydoc.h is automatically generated in the build directory
#include <vec_sink_c_proc_pydoc.h>

void bind_vec_sink_c_proc(py::module& m)
{

    using vec_sink_c_proc    = ::gr::bokehgui::vec_sink_c_proc;


    py::class_<vec_sink_c_proc, gr::bokehgui::base_sink<std::complex<float> >,
        std::shared_ptr<vec_sink_c_proc>>(m, "vec_sink_c_proc", D(vec_sink_c_proc))

        .def(py::init(&vec_sink_c_proc::make),
           py::arg("vlen"),
           py::arg("name"),
           py::arg("nconnections"),
           D(vec_sink_c_proc,make)
        )
        




        
        .def("reset",&vec_sink_c_proc::reset,       
            D(vec_sink_c_proc,reset)
        )

        ;




}








