# Not cross-platform, but works

name: withAptitude

# Run this workflow manually from the Actions tab
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "populate"
  populate:
    # Run on a single platform or use a matrix to test against several
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        gr: [3.9., 3.10.]
        bokeh: [2.3.1., 2.4.2.]
      fail-fast: false
    env:
       TMPTMPDIR: /tmp
       OS_CHOICE: ${{ matrix.os }}
       
    # Steps represent a sequence of tasks that will be executed as part of the job
    name: gr-bokeh with gnuradio ${{ matrix.gr }} and bokeh ${{ matrix.bokeh }} on ${{ matrix.os }}
    steps:
      - name: Essential housekeeping
        run: |
          mkdir -p ~/artifacts
          sudo apt update
          
      - name: Security first
        if: true
        run: |
          sudo apt install -y software-properties-common apt-utils 
          sudo apt install -y unattended-upgrades
          sudo unattended-upgrade -d >~/artifacts/securityFirst.log

      - name: Performance second
        if: true
        run:  sudo apt upgrade -qy

      - name: Build essentials 
        if: true
        run: |
          sudo apt install -qy build-essential cmake cmake-curses-gui ninja-build
          sudo apt install -qy texinfo gawk g++ swig
          sudo apt install -qy npm nodejs
          sudo npm install -g npm@8.5
 
      - name: Install GNUradio PPA 3.9
        if: ${{ matrix.os == 'ubuntu-latest'  && matrix.gr == '3.9.' }}
        run: |
          sudo add-apt-repository -y ppa:gnuradio/gnuradio-releases-3.9
          sudo apt update

      - name: Install GNUradio PPA 3.10
        if: ${{ matrix.os == 'ubuntu-latest'  && matrix.gr == '3.10.' }}
        run: |
          sudo add-apt-repository -y ppa:gnuradio/gnuradio-releases
          sudo apt update
          sudo apt install -qy libiio-dev libad9361-dev libspdlog-dev python3-packaging

      - name: Install the tangled web 
        if: false
        run: |
          sudo apt install -qy build-essential npm nodejs cmake cmake-curses-gui ninja-build python3-pip
          sudo apt install -qy lrzip cmake g++ libboost-all-dev libgmp-dev swig python3-numpy \
                           python3-mako python3-sphinx python3-lxml doxygen libfftw3-dev \
                           libsdl1.2-dev libgsl-dev libqwt-qt5-dev libqt5opengl5-dev python3-pyqt5 \
                           liblog4cpp5-dev libzmq3-dev python3-yaml python3-click python3-click-plugins \
                           python3-zmq python3-scipy python3-gi python3-gi-cairo gir1.2-gtk-3.0 \
                           libcodec2-dev libgsm1-dev
          sudo apt install -qy pybind11-dev python3-matplotlib libsndfile1-dev \
                           python3-pip libsoapysdr-dev soapysdr-tools
          pip install pygccxml
          pip install pyqtgraph
          sudo apt install -qy libiio-dev libad9361-dev libspdlog-dev python3-packaging

      - name: Install gnuradio
        run: |
          sudo apt install -y gnuradio gnuradio-dev

      - name: Blacklist default version of Python 2
        if: true
        run: |
          sudo apt remove --purge -y python || true
          sudo apt autoremove 
          python3 -m pip install --user --upgrade pip
          
      - name: Checkout the current branch
        uses: actions/checkout@master

      - name: Checkout 2.3.1 of bokehjs
        if: ${{ matrix.bokeh == '2.3.1.' }}
        uses: actions/checkout@master
        with:
          repository: bokeh/bokeh
          ref: refs/tags/2.3.1
          path: 'build'
          
      - name: Install bokeh and bokehjs
        if: ${{ matrix.bokeh == '2.3.1.' }}
        run: |
          pip install bokeh
          cd build
          npm init -y
          npm install
          pushd bokeh
          npm install
          cd ../bokehjs
          npm install
          popd
          python3 ./setup.py install --build-js || sudo python3 ./setup.py install --install-js 

      - name: use pip to install bokeh
        if: ${{ matrix.bokeh == '2.4.2.' }}
        run: |
          pip install bokeh

      - name: Build gr-bokehgui with CMake
        run: |
          python3 -m bokeh info >~/artifacts/bokeh.log
          mkdir -p build && cd build
          cmake ..
          cmake --build .
          sudo cmake --build . --target install          
          
      - name: Did it work?
        run: |
          cd examples
          grcc tutorial.grc
          cp tutorial.py ~/artifacts
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts gr=${{matrix.gr}} bokeh=${{matrix.bokeh}} 
          path: ~/artifacts/
